== Vaadin integration

The `holon-vaadin` artifact is the main entry point to use the Holon platform Vaadin integration.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin</artifactId>
<version>{revnumber}</version>
----

== Component builders

A complete set of _fluent_ builders is available to create and configure the most common Vaadin standard components and the ones provided by the Holon platform Vaadin integration module.

TIP: See <<UIComponents>> for a list of the additional components made available by the Holon platform Vaadin integration module.

All the builders can be obtained using the link:{apidir}/com/holonplatform/vaadin/components/Components.html[Components^] interface, which is organized in  sub-interfaces by component kind.

.Components builders structure
|===
|Sub-interface |Provides

|*[NONE]*
|A set of _configure(*)_ methods to setup existing standard component instances and a set of methods to obtain the _fluent_ builders for standard Vaadin components, such as `Label`, `Button`, and standard layout components.

|*input*
|Builders for different data type `Input` components, including selection components. Furthermore, provides builder to create input _forms_.

|*view*
|Builders for `ViewComponent` components and view _forms_.

|*listing*
|Builders for components which represent a list of _items_.
|===

TIP: For each UI displayed text of a component (for example, the component caption or description), the builders provide the opportunity to set a _localizable_ text, using a `Localizable` object or directly providing the _message code_ and the _default message_ of the localizable text. In order for the localization to work, a `LocalizationContext` must be available as a context resource. See the link:holon-core.html#i18n[Internationalization] documentation for further information.

[[UIComponents]]
== UI Components

The Vaadin module provides a set of components which extend or decorates the standard components set. The available components are described below.

=== Input

The link:{apidir}/com/holonplatform/vaadin/components/Input.html[Input^] interface represents a component that has a user-editable value, which can be read and setted using the methods provided by the The link:{apidir}/com/holonplatform/vaadin/components/ValueHolder.html[ValueHolder^] super interface.

Input components supports the _read-only_ (to prevent the user from changing the value) and _required_ (to show a suitable indicator along with the field) modes.

Input components supports `ValueChangeListener` registration to listen to input value changes.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input1,indent=0]
----
<1> Create and configure a `String` value type `Input` field.
<2> Set a value
<3> Get the value
<4> Add a `ValueChangeListener`

The concrete Vaadin `Component`, which represents the UI input element, can be obtained through the `getComponent()` method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input2,indent=0]
----
<1> Create and configure a `LocalDate` value type `Input` field.
<2> Get the input `Component`, which can be used to display the input field in UI.

An `Input` component can be obtained from a standard Vaadin `HasValue` component using the `from(...)` static method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input3,indent=0]
----

Another way to obtain a standard Vaadin `HasValue` component from an input component is to use the `asField()` input builder method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input4,indent=0]
----
<1> Create select field using `Locale` data type and obtain it as `Field`, i.e. as a standard `HasValue` component.

=== ValidatableInput

The link:{apidir}/com/holonplatform/vaadin/components/ValidatableInput.html[ValidatableInput^] interface represents an `Input` component which supports value validation using the standard Holon platform `Validator` interface.

Value validation can be triggered each time the input value changes, using `setValidateOnValueChange` method.

A link:{apidir}/com/holonplatform/vaadin/components/ValidationStatusHandler.html[ValidationStatusHandler^] can be used to control how the validation errors are notified to the user, listening to validation status change events.

By default, the standard Vaadin component error notification is used.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input5,indent=0]
----
<1> Create a `ValidatableInput` from a String input
<2> Add a validator to check the input value is a valid e-mail address
<3> Add a validator to check the input value is maximum 100 characters long
<4> Set validation status handler which shows a notification when the input in invalid
<5> Perform the input value validation
<6> Triggers validation when input value changes

A `ValidatableInput` can be obtained from an existing `Input` or `HasValue` component instance or using the appropriate builder.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input6,indent=0]
----
<1> Create a `ValidatableInput` from a String `Input`
<2> Create a `ValidatableInput` from a String type `HasValue` component
<3> Create a `ValidatableInput` using the input builder
<4> Add a default _required_ (the input is not empty) validator using the provided error message
<5> Add a standard validator

=== Selectable Input

When the Input values must be selected from a specific set, a _selectable_ Input type can be used. Two _selectable_ Input types are available:

* The link:{apidir}/com/holonplatform/vaadin/components/SingleSelect.html[SingleSelect^] Input, in which at most one item can be selected at a time;
* The link:{apidir}/com/holonplatform/vaadin/components/SingleSelect.html[MultiSelect^] Input, in which multiple items can be selected at the same time.

Both _selectable_ Input types extends the link:{apidir}/com/holonplatform/vaadin/components/Selectable.html[Selectable^] interface, which provides methods to check if some item is selected, obtain the selected item/s and change the current selection. Furthermore, a `SelectionListener` can be registered to listen to selection changes.

.SingleSelect example
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable1,indent=0]
----
<1> Create a `SingleSelect` Input using the `TestData` class as selection item type
<2> Select a value using the default `setValue()` Input method
<3> Select a value using `select()` method
<4> Deselect the value using the default `clear()` Input method
<5> Deselect the value using the `deselectAll()` method
<6> Check whether a value is selected
<7> Add a selection listener

.MultiSelect example
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable2,indent=0]
----
<1> Create a `MultiSelect` Input using the `TestData` class as selection item type
<2> Select a set of values using the default `setValue()` Input method
<3> Add a value to current selection using the `select()` method
<4> Remove a value from current selection
<5> Deselect the value using the default `clear()` Input method
<6> Deselect the value using the `deselectAll()` method
<7> Check whether a value is selected
<8> Add a selection listener

==== Rendering mode

The visual aspect of the _selectable_ Input can be configured using the `RenderingMode` enumeration. According to the rendering mode, a suitable UI component will be used to implement the Input.

NOTE: The default rendering modes are `SELECT` for `SingleSelect` inputs and `OPTIONS` for `MultiSelect` inputs.

|===
|Rendering mode |SingleSelect UI component |MultiSelect UI component

|*NATIVE_SELECT*
|`com.vaadin.ui.NativeSelect`
|_not supported_

|*SELECT*
|`com.vaadin.ui.ComboBox`
|`com.vaadin.ui.ListSelect`

|*OPTIONS*
|`com.vaadin.ui.CheckBoxGroup`
|`com.vaadin.ui.RadioButtonGroup`
|===

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable3,indent=0]
----
<1> Create a `SingleSelect` using the *OPTIONS* rendering mode: a CheckBox group UI component will be used
<2> Create a `MultiSelect` using the *SELECT* rendering mode: a ListSelect UI component will be used

==== Selection items data source

The data source of the available items for a _selectable_ input can be configured in the following ways:

* Using a fixed set of items, which can be provided using the `addItem(...)` or `items(...)` methods of the select input builder;
* Using a Holon platform `ItemDataSource` data provider;
* Using a standard Vaadin `DataProvider`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable4,indent=0]
----
<1> Create a select input using an explicitly provided items set
<2> Create a select input using a Holon platform `ItemDataSource`
<3> Create a select input using a Vaadin `DataProvider`

==== Item captions and icons

The _selectable_ input builders allow to explicitly set the selection item *captions* and *icons*. As for the items caption, the Holon platform *localization* architecture is supported, and the builders provides methods to specify the caption using a `Localizable` or a _message code_.

TIP: In order for the localization to work, a `LocalizationContext` must be available as a context resource. See the link:holon-core.html#i18n[Internationalization] documentation for further information.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable5,indent=0]
----
<1> Set the item caption for the `ONE` item
<2> Set the localizable item caption for the `ONE` item, providing a default caption and a translation message code
<3> Set the item icon for the `ONE` item

Furthermore, the `ItemCaptionGenerator` and the `ItemIconGenerator` interfaces can be used to provide custom selection items *captions* and *icons*. By default, the item caption is obtained using the `toString()` method of the item class and no icon is displayed.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable6,indent=0]
----
<1> Set an item caption generator which provides the item description as item caption
<2> Set an item icon generator

==== SingleSelect caption filter

For `SingleSelect` inputs using *SELECT* rendering mode, the UI component allows the user to type a _filtering_ text to search for a selection item, and such filter by default is referred to item captions.

When using a *fixed item set*, the in-memory caption filter can be customized using the `filteringMode(...)` builder method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable7,indent=0]
----

When using a `ItemDataProvider` or a Vaadin `DataProvider`, an overloaded form of the `dataSource(...)` method can be used, which accept as second parameter a function to provide a suitable query filter using the current user filtering text.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable8,indent=0]
----

==== Using the `Property` model with selectable Inputs

The Holon platform `Property` model is fully supported by the selectable input builder, which allow to create selectable inputs using `PropertyBox` type items and a specific `Property` as selection property (typically, the property which acts as item id).

The selection data type will be the same as the selection property type.

The simplest way to configure a `Property` based selectable input, is by using a `Datastore`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable9,indent=0]
----
<1> Create a `SingleSelect` using the `ID` property as selection property
<2> Set the select data source using a `Datastore`, specifying the `DataTarget` and the set of property to use as query projection
<3> Set an item caption generator which provides the value of the `DESCRIPTION` property as item caption
<4> Set the selected value, which will be of type `Long`, consistent with the `ID` selection property
<5> Get the selected value, which will be of type `Long`, consistent with the `ID` selection property
<6> Refresh the selection items, querying the `Datastore`

One or more `QueryConfigurationProvider` can be used to control the Datastore query configuration, providing additional filters and/or sorts.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable10,indent=0]
----
<1> Set a `QueryConfigurationProvider` which provides a `QueryFilter` to select only the items with the `ID` property that is greater than 0

=== Grouping Inputs in Forms



== Property renderers and presenters


== Data providers


== Device information

