== Vaadin UI integration

The `holon-vaadin` artifact is the main entry point to use the Holon platform Vaadin integration.

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin</artifactId>
<version>{revnumber}</version>
----

[[ComponentsAPI]]
== Component builders

A complete set of _fluent_ builders is available to create and configure the most common Vaadin *components* and the additional components provided by the Holon platform Vaadin module.

TIP: See <<UIComponents>> for a list of the additional components made available by the Holon platform Vaadin module.

All the builders can be obtained by using the link:{apidir}/com/holonplatform/vaadin/components/Components.html[Components^] API, which is organized in  sub-APIs by components category.

The available *component categories* are the following:

|===
|Sub-interface |Provides

|*[NONE]*
|A set of _configure(*)_ methods to setup existing standard component instances and a set of methods to obtain the _fluent_ builders for standard Vaadin components, such as `Label`, `Button`, and standard layout components.

|*input*
|Builders for different data type `Input` components, including selection components. Furthermore, it provides builder to create input _forms_.

|*view*
|Builders for `ViewComponent` components and view _forms_.

|*listing*
|Builders for components which represent a list of _items_.
|===

TIP: For each UI displayed text of a component (for example, the component caption or description), the builders provide the opportunity to set a _localizable_ text, using a `Localizable` object or directly providing the _message code_ and the _default message_ of the localizable text. In order for the localization to work, a `LocalizationContext` must be available as a context resource. See the link:holon-core.html#i18n[Internationalization] documentation for further information.

[[ComponentBuildersCommonFeatures]]
== Component builders common features

The Holon Platform Vaadin component builders make available a set of common features, partly related to standard Vaadin features configuration and partly dedicated to the integration with some core Holon Platform APIs.

For each UI component which extends a standard Vaadin `Component` hierarchy, the builder APIs provide methods to configure all the component attributes and register the supported _listeners_. In addition to the common component configuration attributes, each component builder makes available methods to configure the component specific attributes and supported behaviors.

.Label builder example
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleComponents.java[tag=builder1,indent=0]
----
<1> Obtain a `com.vaadin.ui.Label` component builder
<2> Set the component width to `100%`
<3> Set the component height to `50px`
<4> Add two css style class names
<5> Set the component icon
<6> Set the _caption_
<7> Set the caption to be rendered as HTML
<8> Set the _description_ (tooltip)
<9> Set a generic _data_ value bound to the component
<10> Set the component as hidden (not visible)
<11> Set the component as disabled
<12> Set the component as responsive
<13> Register a `AttachListener`
<14> Register a `DetachListener`
<15> Register a `ContextClickListener`
<16> Set the component `ErrorHandler`
<17> Set the Label content
<18> Set the Label content mode as HTML

For _component container_ component types (for example, Layout components), the builder APIs provides a set of methods to add components to the container to build, also providing layout configuration attributes such as alignment and expand ratio, when supported.

.VerticalLayout builder example
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleComponents.java[tag=builder2,indent=0]
----
<1> Obtain a `com.vaadin.ui.VerticalLayout` component builder
<2> Enable layout margins
<3> Enable layout spacing 
<4> Add components to the layout in given order
<5> Add a component and set the component alignment
<6> Add a component and set the component expand ratio
<7> Add a component and set the component expand ratio to 1 (full)
<8> Add a component and set the component alignment and expand ratio

[[ComponentConfigurators]]
=== Component configurators

When a component instance is already available, the link:{apidir}/com/holonplatform/vaadin/components/Components.html[Components^] API makes available a set of _component configurator_ APIs, which can be used to configure a component instance, using the same API as the component _builders_.

The `configure(AbstractComponent component)` method can be used to obtain a component configurator for a generic `com.vaadin.ui.AbstractComponent`, to setup common component configuration attributes.

Other component confgurator APIs are provided to configure specific components, such a `Label` and `Button`, and the standard Vaadin layout components.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleComponents.java[tag=builder3,indent=0]
----
<1> Label component configurator
<2> VerticalLayout component configurator

[[MessagesLocalization]]
=== Messages localization support

The component builder methods that can be used to configure a _text to display_ for a component supports the *message localization* using the standard link:holon-core.html#i18n[Holon Platform internationalization APIs^].

The message localization attributes can be provided either using:

* A `Localizable` object instance;
* Or directly providing the message localization attributes, such as the *message code*, the *default message* and the optional message localization _arguments_.

A set of _localizable_ message builder methods are available, for example, for standard Vaadin component attributes, such as the component _caption_ and _description_.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleBuilders.java[tag=i18n,indent=0]
----
<1> Set the Button _caption_ using a default caption message (`DefaultCaption`) and a message localization code (`button.caption.code`)
<2> Set a _localizable_ Label content using a `Localizable`

IMPORTANT: In order for the message localization to work, a valid `LocalizationContext` instance must be available as a *context resource* using the default `LocalizationContext` resource key (i.e. the `LocalizationContext` class name). See the link:holon-core.html#LocalizationContext[LocalizationContext documentation^] for details about the `LocalizationContext` API and the link:holon-core.html#Context[Context resources documentation^] for information about the Holon Platform _Context_ architecture.

==== Defer localization

By default, the component messages localization is performed immediately during the component building, when a localizable message is provided at component configuration time. 

Since the Holon Platform localization APIs require that a `LocalizationContext` resource is available to perform messages localization, when this is not possible the messages localization will not work at component configuration time. The `LocalizationContext` resource must be also _localized_, i.e. the current `Locale` is configured and available, in order to ensure messages localization support.

When the `LocalizationContext` resource configuration or localization availability is expected _after_ the component build time, the component builder APIs provide a method to _defer_ the component messages localization: `deferLocalization()`.

This method instructs the builder to resolve any message localization (for example the component caption and description) only when the component is attached to a parent layout, and this means only when the parent layout too is attached to the application UI.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleComponents.java[tag=builder4,indent=0]
----
<1> Set to defer the component messages localization at UI display time

[[DragAndDrop]]
=== Drag and Drop support

The Vaadin module component builders supports component *drag and drop* configuration, allowing to declare a component as _draggable_ and configure the drag mode and attributes and to declare a component as a _drop target_ providing the target configuration and logic to react to a drop event.

The standard Vaadin `DragSourceExtension` and `DropTargetExtension` extensions are used to configure components drag and drop capabilities.

The `dragSource` builder method can be used to declare a component as _draggable_. The provided `Consumer` can be used to configure the `DragSourceExtension` for the component.

The `dropTarget` builder method can be used to declare a component as a _drop target_ and the provided `BiConsumer` can be used to configure the `DropTargetExtension` for the component and to obtain the actual component instance when a drop event occurs.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleBuilders.java[tag=dnd,indent=0]
----
<1> Configure the Label as _draggable_
<2> The `DragSourceExtension` can be configured using the provided `Consumer` function
<3> Configure the VerticalLayout as a _drop target_
<4> The `DropTargetExtension` can be configured using the provided `BiConsumer` function
<5> The second argument of the `BiConsumer` function is the actual VerticalLayout instance, used in this case to add the dropped component to the layout when a drop event occurs

[[UIComponents]]
== UI Components

The Vaadin module provides a set of additional UI components which can be used besides the standard Vaadin components.

=== Input

The link:{apidir}/com/holonplatform/vaadin/components/Input.html[Input^] interface represents a component that provides a user-editable value, which can be read and setted using the methods provided by the The link:{apidir}/com/holonplatform/vaadin/components/ValueHolder.html[ValueHolder^] API.

The `Input` API is parametrized on the value type it manages and the value management is provided by the link:{apidir}/com/holonplatform/vaadin/components/ValueHolder.html[ValueHolder^] API, which provides methods to:

* Set the Input value.
* Read the input value.
* Provide and _empty_ value representation.
* Check whether a value is available.
* Listen to value changes registering one or more link:{apidir}/com/holonplatform/vaadin/components/ValueHolder.ValueChangeListener.html[ValueChangeListener^].

Furthermore, the `Input` API supports two component *state* configuration options:

* *Read-only mode:* When an `Input` is in read-only mode, the user can't change the Input value.
* *Required mode:* When an `Input` is in required mode, a _required indicator_ symbol is visible.

The `Input` API is a general and abstract representation of an UI object which holds a value, the actual Vaadin `Component` representation can be obtained though the `getComponent()` method and used with the standard Vaadin APIs.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=component,indent=0]
----
<1> Create a String type input
<2> Get the actual Input `Component`
<3> Add the Input `Component` to a vertical layout

==== Create an `Input` component

An `Input` component can be created using the link:{apidir}/com/holonplatform/vaadin/components/Components.html[Components^] API, through the *input* sub-interface methods.

A _typed_ `Input` builder method is available for each available `Input` value type. Besides the base `Input` types, as set of methods are available to create *single and multi select* Input components. See <<SelectableInput>> for details.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=builder1,indent=0]
----
<1> `String` type Input
<2> `String` type Input represented as a _text area_
<3> Numeric (`Integer` in this case) type Input
<4> `Boolean` type Input
<5> `Date` type Input with _resolution_ configuration
<6> `LocalDate` type Input
<7> `LocalDateTime` type Input
<8> `Enum` type Input represented with a _single select_
<9> `Enum` type Input represented with a _multi select_

*Input component configuration:*

The `Input` builder API provides methods both for the `Input` attributes al listeners configuration and for the associated Input `Component` configuration, including API methods for specific `Input` and `Component` types.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=builder2,indent=0]
----
<1> Input `Component` configur
<2> Set the Input as read-only
<3> Set the _tabulator index_
<4> Set the Input initial value
<5> Register a `ValueChangeListener`
<6> Register a `FocusListener`
<7> Set the Input _prompt_
<8> Set the String Input max length (the maximum number of cahracters)
<9> Set to treat _blank_ String values (with 0 length or whitespaces only) as `null` values. 
<10> Set the mode how the Input triggers vaue change events

See the next sections for details about the `Input` configuration attributes and features.

==== Obtain an Input component from a `HasValue` Component

An `Input` component can be obtained from a standard Vaadin `HasValue` Component using the `from` static method of the `Input` API.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=builder3,indent=0]
----
<1> Create a `String` type `Input` using a Vaadin `TextField` as concrete implementation

A `com.vaadin.data.Converter` can also be provided to obtain an `Input` component with a different value type from the original field type, providing the presentation to model type value conversion logic and vice-versa.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=builder4,indent=0]
----
<1> Create a `Integer` type `Input` using a Vaadin `TextField` as concrete implementation and providing a `Converter` to convert `String` type presentation values into `Integer` type model values and vice-versa 

==== Obtain a `HasValue` Component from Input builders

The `Input` builder APIs can provide the `Input` instance also a standard Vaadin `HasValue` Component, which is represented by the convenience link:{apidir}/com/holonplatform/vaadin/components/Field.html[Field^] interface.

To obtain a `Field` type Input component, the `Input` builder API `asField()` method can be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=builder5,indent=0]
----
<1> Obtain a `LocalDate` type `Input` builder
<2> Get the `Input` component as a `LocalDate` type `Field`
<3> The obtained `Field` is a `HasValue<LocalDate>` and a `Component`

[[InputConverter]]
==== Input value conversion

The `Input` interface makes available a set of methods to create an `Input` from another `Input` or from a standard Vaadin `HasValue` Component with a different value type, providing a suitable _converter_ to perform value conversions from the presentation value type to the model value type and vice-versa.

The stardard Vaadin `com.vaadin.data.Conveter` API is supported to provide the value conversion logic.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input7,indent=0]
----
<1> Convert a `String` presentation type `Input` into a `Integer` model type `Input` using the standard Vaadin `StringToIntegerConverter`
<2> Obtain a Boolean type `Input` from the `Integer` type one providing the value conversion logic
<3> Obtain a `Long` type `Input` from a `String` type `TextField` using the `StringToLongConverter` converter

Besides the standard Vaadin `com.vaadin.data.Conveter`, the Holon `PropertyValueConverter` can be used, providing the `Property` to which the converter is bound.

TIP: See the link:holon-core.html#PropertyValueConverter[Property value conversion documentation^] for information about the `PropertyValueConverter` API.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=input8,indent=0]
----
<1> The `Boolean` type `Property` to use for the `PropertyValueConverter`
<2> Create a `Boolean` type `Input` from an `Integer` type `Input`, using a the default _numericBoolean_ `PropertyValueConverter`

==== Listening to `Input` value changes

The `Input` API supports link:{apidir}/com/holonplatform/vaadin/components/ValueHolder.ValueChangeListener.html[ValueChangeListener^] registration to listen to `Input` value changes.

The value change event provide the current (changed) `Input` value, the previous (old) `Input` value, the value change source (i.e. the reference to the `Input` component which triggered the value change listeners) and whether the value change was originated by a user action or from server side code.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=valuechange,indent=0]
----
<1> Register a `ValueChangeListener` for the `String` type `Input`
<2> Get the new value that triggered the value change event
<3> Get the value of the `Input` before the value change event occurred
<4> Get whether the event was triggered by user interaction, on the client side, or programmatically, on the server side
<5> Get the source of the value change event, i.e. the `Input` component itself

*Value change mode*

The mode and the frequency with which the value change events are triggered can be customized for the `Input` components which supports it. 

The link:{apidir}/com/holonplatform/vaadin/components/ValueHolder.MaySupportValueChangeMode.html[MaySupportValueChangeMode^] API, extended by the `Input` API, allows to check if the value change mode configuration is supported by a specific `Input` component through the `isValueChangeModeSupported()` method.

If so, the value change mode can be configured specifying:

* The `com.vaadin.shared.ui.ValueChangeMode` enumeration value which represents when and how often `Input` value changes are transmitted from the client to the server.
* Set the value change _timeout_, i.e. how often value change events are triggered, when the `ValueChangeMode` is either `LAZY` or `TIMEOUT`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=valuechangemode,indent=0]
----
<1> Configure the `ValueChangeMode` using the Input builder. The builder methods to configure the value change mode are available only for Input components which support it.
<2> Configure the value change timeout using the Input builder
<3> Check if the value change mode configuration is supported by the `Input` component
<4> Set the value change mode to `BLUR` using the `Input` API

=== ValidatableInput

The link:{apidir}/com/holonplatform/vaadin/components/ValidatableInput.html[ValidatableInput^] interface represents an `Input` component which supports *value validation* using the standard link:holon-core.html#Validator[Holon Platform Validator API^].

A `ValidatableInput` can be obtained in the following ways:

*1. From an existing `Input` or `HasValue` component:* Using the `from` static method of the `ValidatableInput` API.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=validatable1,indent=0]
----
<1> Create a `ValidatableInput` from a String Input
<2> Create a `ValidatableInput` from a `TextField`

*2. Using the `Input` builder:* Using the `validatable()` builder method, which returns a `ValidatableInputBuilder` API that can be used to configure the `ValidatableInput`, for example adding one or more `Validator`, before returning it.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=validatable2,indent=0]
----
<1> Get the builder API to obtain a `ValidatableInput`
<2> Add a default _required_ (the input is not empty) validator using the provided error message
<3> Add a `Validator

==== Registering Validators and perform validation

The `addValidator` method of the `ValidatableInput` API can be used to register value validators for the `Input` component.

The `Validator` API can be used to obtain a set of builtin validators, allowing to specify the validation error message, even using a _localizable_ message code. See the link:holon-core.html#Validator[Holon Platform Validator API^] for details.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=validatable3,indent=0]
----
<1> Create a `String` type `ValidatableInput`
<2> Add a builtin `Validator` to check the Input value is maximum 100 characters long, using the default validation error message
<3> Add a builtin `Validator` to check the Input value is a valid e-mail address, providing a _localizable_ validation error message
<4> Add a `Validator` to check the Input value is at least 3 characters long and provide the validation error message

The actual value validation can be performed using the link:{apidir}/com/holonplatform/vaadin/components/Validatable.html[Validatable^] API, which provides the following methods:

* `validate()`: Validate the current `Input` value using the registered `Validator` s. Throws a `ValidationException` if the value is not valid, which provides the validation error message/s. The `ValidationException` is `Localizable`, providing optional message code and arguments for validation message localization.

* `isValid()`: Returns whether the current `Input` value is valid, swallowing any `ValidationException`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=validatable4,indent=0]
----
<1> Validate the `Input` value. The `ValidationException` is thrown if the validation fails.
<2> Checks whether the current `Input` value is valid, swallowing any `ValidationException`.

==== Automatic validation at `Input` value change

Value validation can be automatically triggered each time the `Input` value changes. 

To enable this behaviour, either the `setValidateOnValueChange` method of the `ValidatableInput` API or the `validateOnValueChange` method of the `ValidatableInput` builder API can be used.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=validatable5,indent=0]
----
<1> Use the `ValidatableInput` builder API to enable the automatic value validation at `Input` value change
<2> Use the `ValidatableInput` API to disable the the automatic value validation at `Input` value change

==== Validation errors notification

By default, the standard Vaadin *component error notification* is used to notify validation errors on `ValidatableInput` components. As per default behaviour, an invalid component is decorated with a proper CSS style class (for example to show a red border around the component itself) and the validation error is notified using a _tooltip_.

To change this behavior and to control how the validation errors are notified to the user, the link:{apidir}/com/holonplatform/vaadin/components/ValidationStatusHandler.html[ValidationStatusHandler^] API can be used.

A `ValidationStatusHandler` listens to validation status change events and the provided validation event can be used to:

* Obtain the current component *validation status*: `UNRESOLVED` (no value validation has been made yet), `VALID` (validation passed), `INVALID` (validation failed).
* Obtain the current *validation error messages* if the component is in the `INVALID` status. The error messages can be obtained as `Localizable` to support message localization.
* Get the *source component* against whom the validation was performed.

The `ValidationStatusHandler` can be configured either using the `setValidationStatusHandler` method of the `ValidatableInput` API or the `validationStatusHandler` method of the `ValidatableInput` builder API.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=validatable6,indent=0]
----
<1> Use the `ValidatableInput` builder API to configure a `ValidationStatusHandler` 
<2> Use the `ValidatableInput` API to configure a `ValidationStatusHandler` 

The `ValidationStatusHandler` also provides static methods to obtain a default validation status handler either using a `Label` component or a Vaadin `Notification` component.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInput.java[tag=validatable7,indent=0]
----
<1> Create a `ValidationStatusHandler` using a `Label` to display validation errors.
<2> Create a `ValidationStatusHandler` using a `Notification` to notify validation errors.

[[SelectableInput]]
=== Selectable Input

When the Input values must be selected from a specific set, a _selectable_ `Input` type can be used. Two _selectable_ Input types are available:

* The link:{apidir}/com/holonplatform/vaadin/components/SingleSelect.html[SingleSelect^] Input, in which *at most one item* can be selected at a time;
* The link:{apidir}/com/holonplatform/vaadin/components/SingleSelect.html[MultiSelect^] Input, in which *multiple items* can be selected at the same time.

Both _selectable_ `Input` types extends the link:{apidir}/com/holonplatform/vaadin/components/Selectable.html[Selectable^] API, which provides methods to check if some item is selected, obtain the selected item/s and change the current selection. 

A _selectable_ `Input` can be obtained using the link:{apidir}/com/holonplatform/vaadin/components/Components.html[Components^] API, through the `singleSelect` and `multiSelect` methods and their specializations.

Furthermore, a link:{apidir}/com/holonplatform/vaadin/components/Selectable.SelectionListener.html[SelectionListener^] can be registered to listen to selection changes.

.SingleSelect example
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable1,indent=0]
----
<1> Create a `SingleSelect` Input using the `TestData` class as selection item type
<2> Select a value using the default `setValue()` Input method
<3> Select a value using `select()` method
<4> Deselect the value using the default `clear()` Input method
<5> Deselect the value using the `deselectAll()` method
<6> Check whether a value is selected
<7> Add a selection listener

.MultiSelect example
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable2,indent=0]
----
<1> Create a `MultiSelect` Input using the `TestData` class as selection item type
<2> Select a set of values using the default `setValue()` Input method
<3> Add a value to current selection using the `select()` method
<4> Remove a value from current selection
<5> Deselect the value using the default `clear()` Input method
<6> Deselect the value using the `deselectAll()` method
<7> Check whether a value is selected
<8> Add a selection listener

==== Rendering mode

The visual aspect of the _selectable_ Input can be configured using the `RenderingMode` enumeration. According to the rendering mode, a suitable UI component will be used to implement the Input.

NOTE: The default rendering modes are `SELECT` for `SingleSelect` inputs and `OPTIONS` for `MultiSelect` inputs.

|===
|Rendering mode |SingleSelect UI component |MultiSelect UI component

|*NATIVE_SELECT*
|`com.vaadin.ui.NativeSelect`
|_not supported_

|*SELECT*
|`com.vaadin.ui.ComboBox`
|`com.vaadin.ui.ListSelect`

|*OPTIONS*
|`com.vaadin.ui.CheckBoxGroup`
|`com.vaadin.ui.RadioButtonGroup`
|===

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable3,indent=0]
----
<1> Create a `SingleSelect` using the *OPTIONS* rendering mode: a `CheckBox` group UI component will be used
<2> Create a `MultiSelect` using the *SELECT* rendering mode: a `ListSelect` UI component will be used

==== Selection items data source

The data source of the available items for a _selectable_ `Input` can be configured in the following ways:

* Using a fixed set of items, which can be provided using the `addItem(...)` or `items(...)` methods of the select input builder.
* Using a Holon Platform link:{apidir}/com/holonplatform/vaadin/data/ItemDataProvider.html[ItemDataProvider^].
* Using a standard Vaadin `DataProvider`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable4,indent=0]
----
<1> Create a select input using an explicitly provided items set
<2> Create a select input using a Holon platform `ItemDataProvider`
<3> Create a select input using a Vaadin `DataProvider`

==== Item captions and icons

The _selectable_ input builders allow to explicitly set the selection item *captions* and *icons*. For the items caption configuration, the Holon Platform *localization* architecture is supported, and the builders provide methods to specify the captions using a `Localizable` object or a _message code_.

See <<MessagesLocalization>> for details about messages localization.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable5,indent=0]
----
<1> Set the item caption for the `ONE` item
<2> Set the localizable item caption for the `ONE` item, providing a default caption and a translation message code
<3> Set the item icon for the `ONE` item

Furthermore, the `ItemCaptionGenerator` and the `ItemIconGenerator` interfaces can be used to provide custom selection items *captions* and *icons*. 

By default, the item caption is obtained using the `toString()` method of the item class and no icon is displayed.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable6,indent=0]
----
<1> Set an item caption generator which provides the item description as item caption
<2> Set an item icon generator

==== `SingleSelect` caption filter

For the `SingleSelect` type Inputs which use the *SELECT* rendering mode, the UI component allows the user to type a _filtering_ text to search for a selection item, and such filter by default is referred to item captions.

When using a *fixed item set*, the in-memory caption filter can be customized using the `filteringMode(...)` builder method.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable7,indent=0]
----

When using a `ItemDataProvider` or a Vaadin `DataProvider`, an overloaded form of the `dataSource(...)` method can be used, which accept as second parameter a function to provide a suitable query filter using the current user filtering text.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable8,indent=0]
----

==== Using the `Property` model with _selectable_ Inputs

The link:holon-core.html#Property[Holon platform Property model^] is fully supported by the selectable Input builders, which allows to create selectable Inputs using `PropertyBox` type items and a specific `Property` as selection property (typically, the property which acts as item id).

The selection data type will be the same as the selection property type.

The simplest way to configure a `Property` based selectable input, is by using a link:holon-core.html#Datastore[Datastore^].

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable9,indent=0]
----
<1> Create a `SingleSelect` using the `ID` property as selection property
<2> Set the select data source using a `Datastore`, specifying the `DataTarget` and the set of property to use as query projection
<3> Set an item caption generator which provides the value of the `DESCRIPTION` property as item caption
<4> Set the selected value, which will be of type `Long`, consistent with the `ID` selection property
<5> Get the selected value, which will be of type `Long`, consistent with the `ID` selection property
<6> Refresh the selection items, querying the `Datastore`

One or more `QueryConfigurationProvider` can be used to control the `Datastore` query configuration, providing additional query filters and/or sorts.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable10,indent=0]
----
<1> Set a `QueryConfigurationProvider` which provides a `QueryFilter` to select only the items with the `ID` property that is greater than 0

===== Selection model converter

When the Holon platform `Property` model is used for selectable Inputs and the selection value type is not a `PropertyBox`, i.e. the selection items are not of the same type of the `Input` value type, a conversion function is required to obtain the `PropertyBox` item from a selection value when the value is setted in the Input component, either using `setValue(...)` or `select(...)`.

For example, if a `String` type `Property` is declared as selection property, the `Input` value will be the the value of the selection property (of `String` type), while the selection items are `PropertyBox`.

When a `Datastore` is provided as the data source of the select, a default item converter is configured. The default item converter tries to obtain the `PropertyBox` item by performing a query on the `Datastore` and using a filter predicate to get the item for which the selection property value is equal to the value to select, assuming that the selection property acts as primary key.

To change the default conversion strategy, a custom item converter can be provided to the select input builder using the `itemConverter(...)` method:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleSelectable.java[tag=selectable11,indent=0]
----
<1> Set an `ItemConverter` providing the query to perform to obtain the item `PropertyBox` from the selection `ID` property value 

[[PropertyInputGroup]]
=== Input groups (Forms)

The link:{apidir}/com/holonplatform/vaadin/components/PropertyInputGroup.html[PropertyInputGroup^] component allows to group and manage a set of `Input` fields, relying on the `Property` model and using  `PropertyBox` objects to collect, set and provide the Input values.

TIP: See the link:holon-core.html#Property[Property] documentation for further information about the Holon platform `Property` model.

A `PropertyInputGroup` is bound to a set of properties, and for each property an `Input` field is made available to set and get the property value. Each property has to be bound to an `Input` field with a consistent value type.

The property values are setted and obtained using the `PropertyBox` data container, with the same property set of the input group.

The property values are automatically updated in the current `PropertyBox` according to any user modification made through the input's UI components.

The property input group supports `ValueChangeListener` registration to be notified when the group `PropertyBox` value changes.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group1,indent=0]
----
<1> Create a `PropertyInputGroup` using the `PROPERTIES` property set
<2> Bind the `ID` property to a `Long` type Input field
<3> Bind the `DESCRIPTION` property to a `String` type Input field
<4> Set the property values using a `PropertyBox` instance
<5> Get the property values as a `PropertyBox` instance
<6> Add a group `ValueChangeListener`

The default Holon platform `PropertyRenderer` architecture can be used to automatically generate a suitable Input component for a `Property`, according to its type.

The `bind(...)` builder method can therefore be used to override the default property input generation only when a custom `Input` type is required.

TIP: See <<RenderersPresenters>> for further information about property renderers.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group2,indent=0]
----
<1> The property `Input` fields are automatically generated using the available `PropertyRenderer` from the default registry

==== Read-only properties

A property can be setted as *read-only*, to prevent the modification of its value. When a property is read-only, the `Input` component will be in read-only mode too, preventing the user from changing the value.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group3,indent=0]
----
<1> The `ID` property is setted as read-only, preventing the user from changing the property value

==== Hidden properties

A property can be setted as *hidden*. When a property is hidden, it is part of the group property set and its value will be preserved in the `PropertyBox` instances, but no `Input` component will be generated and bound to the property itself, so its value will never be visible on the user interface.

Inputs bound to hidden properties are never returned from the `PropertyInputGroup` methods which allow to inspect the available binding, such as `getInputs()`, `getInput(Property<T> property)` or `stream()`.

The `hidden(Property property)` method of the group builder can be used to set a property as hidden.

==== Default property values

A *default value* can be provided for a property. If available, the default value will be used as property value when the corresponding Input component is empty (i.e. has no value).

The `defaultValue(Property<T> property, DefaultValueProvider<T> defaultValueProvider)` method of the group builder can be used to set a default value for a property.

=== Input group validation

A `PropertyInputGroup` support both property value and group value validation, using both standard Holon platform `Validator` and Vaadin validators.

A set of `required(...)` group builder methods are provided to add a _required_ validator to a property (i.e. a validator that check the value is not null or empty) and to show the required indicator symbol along with the property input component. 

When a validator in bound to the overall input group, the value to validate will be represented by the `PropertyBox` which contains all the current property values.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group4,indent=0]
----
<1> Add a validator bound to the `DESCRIPTION` property to check that the value size is not greater than 100 characters
<2> Add a _required_ validator to the `ID` property
<3> Add a _required_ validator to the `ID` property providing a custom validation error message
<4> Add an overall validator which reads the `ID` property value from the group `PropertyBox` and checks it is greater than 0

The input group validation is performed invoking all the available property validators, and then the overall group validators, if any.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group5,indent=0]
----
<1> Explicit group validation: if some kind of validation failure occurs, a `ValidationException` is thrown
<2> Using the default `getValue()` method, the validation is triggered automatically, and a  `ValidationException` is thrown if validation fails
<3> The `getValue(boolean validate)` method can be used to skip value validation
<4> The `getValueIfValid()` returns an Optional, which contains the `PropertyBox` value only if the validation succeded

A link:{apidir}/com/holonplatform/vaadin/components/ValidationStatusHandler.html[ValidationStatusHandler^] can be used to control how the validation errors are notified to the user, listening to validation status change events.

The property input group supports `ValidationStatusHandler` configuration both for property and overall validation.

Furthermore, the input group builder provides two methods to control if the validation failures are to be collected and all notified to the user or if the validation has to stop at first failure, both from a properties or a group point of view.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group6,indent=0]
----
<1> Set to stop overall validation at first failure
<2> Set to stop properties validation at first failure
<3> Set the overall `ValidationStatusHandler`
<4> Set the properties `ValidationStatusHandler`

TIP: A property input group `ValidationStatusHandler` setter method which accept a `Label` is provided as a shorter to use a standard Vaadin `Label` to notify validation errors.

=== Handling value changes

The `PropertyInputGroup` builder provides methods to add `ValueChangeListener` to the `Input` bound to group property set.

In addition to the standard `ValueChangeListener`, the link:{apidir}/com/holonplatform/vaadin/components/PropertyInputBinder.PropertyInputValueChangeListener.html[PropertyInputValueChangeListener^] interface is also supported to listener to Property/Input value changes.

The `PropertyInputValueChangeListener` provides the current `PropertyInputBinder` reference, besides of the standard `ValueChangeEvent`. The `PropertyInputBinder` makes available several methods to inspect the input group to which the value change source belongs, for example in order to obtain the values of other `Input` components.

Through the `PropertyInputGroup` builder, the value change mode configuration can also be setted up, allowing to change the overall `ValueChangeMode` (for all inputs), or the `ValueChangeMode` for a specific property.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group7,indent=0]
----
<1> Add an overall value change listener
<2> Add a value change listener to the Input bound to the `DESCRIPTION` property
<3> Add a `PropertyInputValueChangeListener` to the Input bound to the `DESCRIPTION` property, which provides the current `PropertyInputBinder` to inspect all available group inputs
<4> Set the default `ValueChangeMode` for all inputs
<5> Set the `ValueChangeMode` only for the Input bound to the `DESCRIPTION` property
<6> Set the value change timeout to 500 ms only for the Input bound to the `DESCRIPTION` property

=== Dealing with Virtual properties

By default, the `PropertyInputGroup` renders as an Input all the properties of the property set that has been provided at build time, including any `VirtualProperty`.

Since a `VirtualProperty` is a *read-only* property, the `Input` bound to a `VirtualProperty` is configured in read-only mode.

If the `VirtualProperty` value is calculated using the values of other properties of the `PropertyInputGroup` property set, can be useful to _refresh_ the displayed `Input` value bound to the virtual property when one or more property of set changes.
For this purpose, the `refresh(...)` methods of the `PropertyInputGroup` can be used. This methods are available from the `PropertyInputBinder` super-interface. You can refresh a specific property or all the properties of the set, even only the read-only ones.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=group8,indent=0]
----
<1> Add a `PropertyInputValueChangeListener` to the Input bound to the `DESCRIPTION` property, and refresh the `VIRTUAL` property Input value when the `DESCRIPTION` property Input value changes

If the `PropertyInputGroup` contains some read-only properties but you don't want to display the corresponding Input components, the `excludeReadOnlyProperties()` builder method can be used.

=== Input Forms

The link:{apidir}/com/holonplatform/vaadin/components/PropertyInputForm.html[PropertyInputForm^] represents an `Input` group bound to a `Property` model which is also a UI `Component`, and can be used to display and manage the `Input` components in the UI.

It is a <<PropertyInputGroup>>, from which inherits all the `Input` generation, configuration and management features, using a `PropertyBox` to set and get the property values bound to each Input component.

It extends the link:{apidir}/com/holonplatform/vaadin/components/ComposableComponent.html[ComposableComponent^] interface, which represents an UI component with a base layout and the capability to _compose_ a set of UI components on this layout.

The `Composer` interface is used to _compose_ the `Input` components on the UI, and must be provided to the `PropertyInputForm`, along with the base layout component on which the `Input` components will be organized.

NOTE: The `ComposableComponent` interface provides the `componentContainerComposer()` static method to obtain a default _composer_ which uses a Vaadin `ComponentContainer` as base layout.

The inputs composition is triggered by using the `compose()` method. The `PropertyInputForm` builder provides a `composeOnAttach(...)` method to set whether to automatically trigger the components composition when the form is attached to a parent layout, and this is the standard behaviour.

Furthermore, a `initializer(...)` builder method is made available to perform custom configuration of the base layout component.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=form1,indent=0]
----
<1> Create a `PropertyInputForm` with given property set using a FormLayout as base layout, and using the default composer
<2> Set a custom `Composer` to compose the Input components on the form layout
<3> Set the form value using a `PropertyBox`
<4> Get the form value

A set of default builder factory methods are provided to use the most common Vaadin layout components as form base content.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleInputGroup.java[tag=form2,indent=0]
----
<1> Create a `PropertyInputForm` using a `FormLayout` as base content
<2> Create a `PropertyInputForm` using a `VerticalLayout` as base content
<3> Create a `PropertyInputForm` using a `HorizontalLayout` as base content
<4> Create a `PropertyInputForm` using a `GridLayout` as base content and setting an _initializer_ function to perform GridLayout configuration

=== View components

The link:{apidir}/com/holonplatform/vaadin/components/ViewComponent.html[ViewComponent^] represents a UI component which can be used to display a value on the user interface. Unlike a `Input` component the value cannot be changed by the user.

As a `ValueHolder`, the view component value can be setted and obtained using the `setValue` and `getValue` methods.

The actual UI component to display is obtained form the `getComponent()` method.

A Vaadin `Label` is used for the default `ViewComponent` implementation, and a default view component can be built using the default builder which can be obtained from the `builder(Class valueType)` method or from the `Components.view` interface.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleViewComponent.java[tag=view1,indent=0]
----
<1> Create and configure a `ViewComponent` with a `String` value type
<2> Set the value
<3> Get the value

==== View component Groups and Forms

Just like the `Input` components, the `ViewComponent` s can be organized in _groups_ (using the link:{apidir}/com/holonplatform/vaadin/components/PropertyViewGroup.html[PropertyViewGroup^]) or in _forms_ (using the link:{apidir}/com/holonplatform/vaadin/components/PropertyViewForm.html[PropertyViewForm^]). Unlike the _group_, the _form_ is a UI component which can be displayed in the user interface, composing the view components on a base layout.

These component containers rely on the `Property` model to bind each view component to a `Property` value and they use a `PropertyBox` to provide the property values to show.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleViewComponent.java[tag=view2,indent=0]
----
<1> Create a `PropertyViewGroup`
<2> Create a `PropertyViewForm` using a `VerticalLayout` as base layout
<3> Create a `PropertyViewForm` using a `FormLayout` as base layout and providing a custom components composer
<4> Set the form value using a `PropertyBox`
<5> Get the form value

=== Composable components setup

Each `ComposableComponent` (such as `PropertyInputForm` and `PropertyViewForm`) is _scrollable_ by default, using the Vaadin `v-scrollable` style name.

Furthermore, the builders support the `ComponentsWidthMode` strategy, which can be configured to control if and how the component has to adjust the width of the children component composed using a `Composer`.

The available modes are:

* `NONE`: The width of each Component will not be altered
* `AUTO`: The width of each component will adjusted according to parent layout width: if the parent layout has not undefined width, the components width will be setted to 100%
* `FULL`: The width of each component will always be setted to 100%

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleComposable.java[tag=wmode,indent=0]
----
<1> Set the `ComponentsWidthMode` to `FULL`: all the form Components will be 100% wide

==== Component configurators

The `ComposableComponent` builders allow to provide custom _configurators_ to configure the UI components associated with the properties to be rendered.

For each `Property` of the component property set, you can provide a `Consumer` to use a `ComponentConfigurator`, which makes available a complete set of methods to configure the `Component` associated with the property before rendering it in UI. For example, you can set the component size, the icon, the description and so on.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleComposable.java[tag=ccfg,indent=0]
----
<1> Configure the `ID` property Component
<2> Configure the `DESCRIPTION` property Component

== Item listing

The link:{apidir}/com/holonplatform/vaadin/components/ItemListing.html[ItemListing^] component can be used to display a set of items as tabular data. By default, it is backed by a Vaadin `Grid` as concrete UI component.

Each item _property_ to display is bound to a _column_, and a Property *id* is used to bind the item property to the listing column.

The `ItemListing` is a link:{apidir}/com/holonplatform/vaadin/components/Selectable.html[Selectable^] component, supporting items selection in single or multiple mode.

The `ItemListing` interface provides a set of methods to control the listing appearance, showing and hiding columns, sorting and refreshing the item set, and so on.

Two `ItemListing` sub-interfaces are available to use this component:

* link:{apidir}/com/holonplatform/vaadin/components/BeanListing.html[BeanListing^]: Uses a Java Bean as item type and the listing column ids are the bean property names. 
* link:{apidir}/com/holonplatform/vaadin/components/PropertyListing.html[PropertyListing^]: Uses a `PropertyBox` as item type and the listing column ids are the `Property` of the provided property set.

=== BeanListing

A link:{apidir}/com/holonplatform/vaadin/components/BeanListing.html[BeanListing^] can be obtained providing the Java Bean class to use as item type.

The listing columns will be generated inspecting the *bean class* to detect the available bean properties, and the column ids will be the bean property names.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=beanListing,indent=0]
----
<1> Create a `BeanListing` using the `TestData` bean class
<2> Set the column header for the `id` item (bean) property
<3> Set the column header for the `description` item (bean) property
<4> Refresh the items set

=== PropertyListing

A link:{apidir}/com/holonplatform/vaadin/components/PropertyListing.html[PropertyListing^] can be obtained by providing the `Property` set to use for the listing items.

The listing columns will be generated according to the item property set `Property` types and each column will be identified by the `Property` itself.

For each property:

* The property _caption_, if available, will be used as column header. The caption/header localization is fully supported and performed if a `LocalizationContext` is available;
* The cells of the column which corresponds to a property will be rendered according to the property type and relying on the available property value _presenters_;
* For any property of `com.vaadin.ui.Component` type, a `ComponentRenderer` will be automatically used to render the Vaadin components in the cells.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=propertyListing,indent=0]
----
<1> Create a `PropertyListing` using given `Property` set

=== Items data source

To build an item listing, the *data source* of the items must be provided using the link:{apidir}/com/holonplatform/vaadin/data/ItemDataProvider.html[ItemDataProvider^] interface.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing1,indent=0]
----
<1> Create a `PropertyListing` and provide an `ItemDataProvider` as data source

Furthermore, an link:{apidir}/com/holonplatform/vaadin/data/ItemIdentifierProvider.html[ItemIdentifierProvider^] should be configured to provide the item *identifiers*, expecially for the item selection consistency. The default behaviour is to use the item itself as its own identifier, which it is not always the right semantic to use, expecially for `PropertyBox` type objects.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing2,indent=0]
----
<1> Create a `PropertyListing` and provide an `ItemDataProvider` as data source, along with an `ItemIdentifierProvider` which provides the value of the `ID` property as item id
<2> A shorter builder method to use the `ID` property as item identifier

The item listing builders make available convenience methods to use a `Datastore` as data source, providing the `DataTarget` to use as target of the query on the backend data (for example, the name of a RDBMS table).

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing3,indent=0]
----
<1> Create a `PropertyListing` and use a `Datastore` to build a data source which performs a query using the `test` data target (which can be, for example, the name of a RDBMS table), the property set of the listing as query projection and the `ID` property as item identifier

=== Columns configuration

The listing component columns can be configured in a number of ways:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing4,indent=0]
----
<1> Set a custom header caption for the `ID` property/column
<2> Set whether the listing columns can be hidden
<3> Set that the `ID` property/column cannot be hidden
<4> Set whether the listing columns can reordered
<5> Set the `ID` property/column cell contents alignment
<6> Set the `DESCRIPTION` property/column as hidden by default
<7> Set the `ID` property/column as not resizable
<8> Set the `ID` property/column width in pixels
<9> Set the `DESCRIPTION` property/column expand ratio
<10> Set the `DESCRIPTION` property/column minimum width
<11> Set the `DESCRIPTION` property/column maximum width
<12> Set the `ID` property/column CSS style generator
<13> Add a listener to be notified when the listing columns order changes
<14> Add a listener to be notified when a property/column is resized 
<15> Add a listener to be notified when a property/column is shown or hidden 

=== Column rendering

The default column rendering can be overridden using a custom vaadin `Renderer`. The `Renderer` must handle the same data type of the property/column for which it is configured. 

Furthermore, a property/column value can be converted to a different value type, and, in this case, a suitable `Renderer` for the converted type must be provided.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing5,indent=0]
----
<1> Set a custom `NumberRenderer` for the `ID` property/column (which is of type `Long`)
<2> Set a converter to convert the `Long` type value of the `ID` property/column into a `String` and a suitable render according to the new value type

=== Listing configuration

The item listing component is highly configurable. Through the builders you can configure:

* The *header appeareance*, adding and removing header rows and joining header columns
* Showing and configuring a *footer* section
* Set a number of column as *frozen*
* Provide *rows CSS style* using a style generator
* Provide item *description* (tooltip) for item rows
* Provide a *item click listener* to listen for user clicks on item rows
* Provide a *row details component* which can be shown for each item row

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing6,indent=0]
----
<1> Set the height of the listing defined by its contents
<2> Set the _frozen_ columns count
<3> Hide all the listing headers
<4> Set the row CSS style generator
<5> Set the item/row description (tooltip) generator
<6> Set the item/row _details_ component generator
<7> Register a item click listener
<8> Add a style class name to the default header row
<9> Append a row to the listing footer and set a style class name for it
<10> Set the footer _generator_ to invoke to update the listing footer contents
<11> Set a post-processor to customize the internal `Grid` component

=== Item selection

The item listing component supports items selection, both in single and multiple mode. The listing can be made selectable by using the `setSelectionMode` method or the `selectionMode` builder method.

Just like any other `Selectable` component, the item listing component provides methods to inspect the current selected item/s and change the current selection.

.Single selection mode
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing7,indent=0]
----
<1> Set the listing _selectable_ in `SINGLE` selection mode
<2> Get the currently selected item, if any
<3> Check whether the given item is selected
<4> Select the given item
<5> Deselect all (clear current selection)

.Multiple selection mode
[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing8,indent=0]
----
<1> Set the listing _selectable_ in `MULTI` selection mode
<2> Get the selected items
<3> Check whether the given item is selected
<4> Select the given item
<5> Deselect all items
<6> Select all items

NOTE: The *select all* checkbox shown in the top left corner of the listing is visible by default. You can control the checkbox visibility using the `selectAllCheckBoxVisibility(...)` method of the item listing builder.

=== Item query configuration

The item listing builder provides a number of methods to control the data source items query, allowing to:

* Set a property/column as *sortable* or not and *override the default sort behaviour*, for example using another property as query sort target or providing a custom `QuerySort`;
* Set a *fixed sort*, which will be always appended to current query sorts
* Set a *default sort*, to be used when no other query sort is configured
* Set a *fixed filter*, which will be always applied to the query
* Register one or more `QueryConfigurationProvider` to provide custom query configuration logic

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing9,indent=0]
----
<1> Set the `ID` property/column as sortable
<2> Set to use the `DESCRIPTION` property to sort the `ID` property/column
<3> Set a custom `QuerySort` for the `ID` property/column
<4> Set a fixed `QuerySort`, which will always to appended to current query sorts
<5> Set the default `QuerySort`, to be used when no other query sort is configured
<6> Set a fixed `QueryFilter`
<7> Add a `QueryConfigurationProvider`

=== Item set management

The item set component provides methods to manage the item set which is provided as the listing data source, to add, update and remove one or more items in the set.

To reflect the item set management operations in the underlyng data source (for example, a RDBMS), the `CommitHandler` interface is used. The `commit(...)` method of that interface is invoked at each item set modification, providing the _added_, _updated_ and _removed_ items. The `CommitHandler` implementation should persist the item set modifications in the concrete data source.

NOTE: When using the `dataSource(...)` builder method which accepts a `Datastore` as data source, a default `CommitHandler` is automatically configured, using the provided `Datastore` to perform the item persistence operations.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing10,indent=0]
----
<1> When using the `Datastore` method of the data source builder, a default `CommitHandler` is automatically configured
<2> You can provide a custom `CommitHandler` using the `commitHandler(...)` builder method
<3> Add an item 
<4> Refresh (update) the item
<5> Remove the item

==== Buffered mode

The item set component supports a *buffered* mode to handle its items set. When in _buffered_ mode, the item set modifications are cached internally and not reflected to the concrete data source until the `commit()` method is called.

A `discard()` method is provided to discards all changes since last commit.

The same `CommitHandler` as before is used to persist the item set modifications, but it is invoked only when the `commit()` method is called.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing11,indent=0]
----
<1> Set the listing in _buffered_ mode
<2> Add an item 
<3> Refresh (update) the item
<4> Remove the item
<5> _commit_ the item set modifications
<6> _discard_ the item set modifications since the last commit

=== Editing items

The item listing component supports line-based editing, where double-clicking a row opens the row editor, using the default Vaadin `Grid` editor. The item listing editor must be enabled using the `editable(true)` method of the builder in order to activate the row editor at double-click.

The *editor fields* to use for each listing property/column will be auto-generated according to the property/column type. This behaviour can be overridden providing custom editor fields for one or more of the listing properties.

The item listing component editor supports *validation*, allowing to register value validators both for the single property/column fields and for the overall value validation. 

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleListing.java[tag=listing12,indent=0]
----
<1> Set the listing as editable
<2> Set the row editor in buffered mode
<3> Set the editor _save_ button caption
<4> Set the editor _cancel_ button caption
<5> Set a property as not editable
<6> Set a custom editor field
<7> Add an overall value validator
<8> Add a property value validator
<9> Set the `ID` property as required, automatically adding a _not empty_ validator

== Dialogs

The Holon Vaadin module provides builders to create and show *dialog* windows. 

A dialog window in represented by the link:{apidir}/com/holonplatform/vaadin/components/Dialog.html[Dialog^] interface, which makes available methods to set the dialog as _modal_, open and close the dialog window and registere a `CloseListener` to be invoked when the dialog is closed.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleDialog.java[tag=dialog1,indent=0]
----
<1> Dialog builder
<2> Set as not draggable
<3> Set as closable
<4> Set as resizable
<5> Set as modal
<6> Set the localizable dialog message
<7> Configure the dialog _OK_ button
<8> Add a close listener
<9> Open (show) the dialog
<10> Close (hide) the dialog

=== Question dialogs

A _question_ dialog is a `Dialog` with a message and two buttons (instead of one) to answer _yes_ or _no_ to a question.

A `QuestionCallback` can be used when the user selects one of the two buttons and the dialog is closed. The callback notifies the selected answer.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleDialog.java[tag=dialog2,indent=0]
----
<1> Question dialog builder
<2> Set the dialog message (the question)
<3> Change the _yes_ button caption
<4> Change the _no_ button caption
<5> Set the answer callback
<6> Build and open the dialog

[[RenderersPresenters]]
== Property renderers and presenters

The Vaadin module takes advantage of the platform foundation _property model_ to provide the most suitable UI components and display values when a `Property` is used.

When a `Property` must be rendered in UI, the components made available by the Vaadin module try to use a suitable `PropertyRenderer`, if available.

By default, the following renderers are automatically registered by the module:

* A link:{apidir}/com/holonplatform/vaadin/components/Input.html[Input^] property renderer
* A link:{apidir}/com/holonplatform/vaadin/components/Field.html[Field^] property renderer, which represents a `HasValue` Vaadin `Component`
* A link:{apidir}/com/holonplatform/vaadin/components/ViewComponent.html[ViewComponent^] property renderer

The `Input` and `Field` property renderers generate a UI component to edit a property value, relying on the property type.

The following types are supported:

* *String*: renders the property as a `TextField`
* *Boolean*: renders the property as a `CheckBox`
* *Enum*: renders the property as a `ComboBox`
* *LocalDate and LocalDateTime*: renders the property as a `DateField` or a `DateTimeField`
* *java.util.Date*: renders the property as a `DateField` or a `DateTimeField`  
* *Number*: renders the property as a `TextField` which only accepts numbers and decimal/group separators

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleRenderers.java[tag=renderers1,indent=0]
----
<1> Render the property as `String` type `Input`
<2> Render the property as `Long` type `Field` (`HasValue` component)
<3> Render the property as `String` type `ViewComponent`

=== Property localization

When a `LocalizationContext` is available as a Context resource, it is used to _localize_ any element to display which supports localization. Concerning to a `Property` related UI component, it is used to:

* Localize the property *caption*, for example when it is used as a listing column header or as a input field caption
* Obtain the *date and time format* to use to display a property value or to edit the property value through an  input field
* Obtain the *number format* to be used to display a property value or to edit the property value through an input field
* Obtain the default *boolean* localized text for the `true` and `false` values

TIP: See the link:holon-core.html#i18n[Internationalization] documentation for further information about localization.

=== Custom property renderers

Relying on the standard property renderers features, custom renderers can be registered to:

* Customize the rendered UI component under certain conditions for the default provided rendering types (`Input`, `Field` and `ViewComponent`)
* Provide the rendering for a custom type

For example, to render a specific `String` type property as *text area*, instead of the default _text field_, an appropriate renderer can be registered and bound to a suitable property condition:

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleRenderers.java[tag=renderers2,indent=0]
----
<1> Create a `Input` property renderer which renders the property as a _text area_
<2> Register the renderer and bind it to a condition which checks the property is exactly the `TEXT` property
<3> From now on, rendering the `TEXT` property as an `Input` field will generate a _text area_ input component

== Vaadin session scope

A *Vaadin session* platform scope is automatically registered by the Holon Vaadin module.

This `ContextScope` is bound to the current `VaadinSession`, looking up context resources using Vaadin Session attributes.

The scope uses `VaadinSession.getCurrent()` to obtain the current Vaadin session, so this scope is active only when invoked within a Vaadin server request thread.

NOTE: See the link:holon-core.html#Context[Context] documentation for further information about context scopes and resources.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleScope.java[tag=sessionscope,indent=0]
----
<1> Create a `LocalizationContext` and set it in Vaadin session using the default context key as attribute name
<2> Get the current `LocalizationContext` context resource, which will be obtained form the Vaadin session, if available

== Device information

The Holon platform Vaadin module makes available the link:{apidir}/com/holonplatform/vaadin/device/DeviceInfo.html[DeviceInfo^] interface, to obtain informations about the *device* in which the application is running.

The `DeviceInfo` object provides informations about the _user agent_ and screen dimensions, and can be obtained by using a `VaadinRequest` or relying on the currently available `VaadinSession`.

[source, java]
----
include::{examplesdir}/com/holonplatform/vaadin/examples/ExampleDevice.java[tag=device,indent=0]
----
