= Holon Vaadin UI
:revnumber: {project-version}
:apidir: ../api/holon-vaadin
:linkattrs:
:sectnums:
:nofooter:
:toc: left
:toclevels: 3

Copyright © 2016-2017

_Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically._

== Introduction

The Holon *Vaadin* module represents the platform support for the https://vaadin.com[Vaadin] web applications framework, focusing on the user interface components and data binding features.

This module provides integration with the platform foundation architecture, such as the `Property` model and the `Datastore` API, the authentication, authorization and localization support.

The _view navigation_ system allows to create web applications focusing on the application functions, which can be represented by _virtual pages_, relying on a robust navigation architecture, with parameters and view lifecycle hooks support.

Furthermore, a complete set of _fluent_ builders is available, to build web application UIs quickly and easily.

== Obtaining the artifacts

The Holon Platform uses https://maven.apache.org[Maven^] for projects build and configuration. All the platform artifacts are published in the *Maven Central Repository*, so there is no need to explicitly declare additional repositories in your project `pom` file.

At the top of each _section_ of this documentation you will find the Maven _coordinates_ (group id, artifact id and version) to obtain the artifact(s) as a dependency for your project.

A *BOM (Bill Of Materials)* `pom` is provided to import the available dependencies for a specific version in your projects. The Maven coordinates for the core BOM are the following:

_Maven coordinates_:
[source, xml, subs="attributes+"]
----
<groupId>com.holon-platform.vaadin</groupId>
<artifactId>holon-vaadin-bom</artifactId>
<version>{revnumber}</version>
----

The BOM can be imported in a Maven project in the following way:

[source, xml, subs="verbatim,quotes,attributes+"]
----
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.holon-platform.vaadin</groupId>
			<artifactId>holon-vaadin-bom</artifactId>
			<version>{revnumber}</version>
			*<type>pom</type>*
			*<scope>import</scope>*
		</dependency>
	</dependencies>
</dependencyManagement>
----

=== Using the Platform BOM

The Holon Platform provides an *overall Maven BOM (Bill of Materials)* to easily obtain all the available platform artifacts.

See link:index.html#obtain-the-platform-artifacts[Obtain the platform artifacts] for details.

// Inclusions

include::_core.adoc[]

include::_navigator.adoc[]

include::_spring.adoc[]

== Loggers

By default, the Holon platform uses the https://www.slf4j.org[SLF4J^] API for logging. The use of SLF4J is optional: it is enabled when the presence of SLF4J is detected in the classpath. Otherwise, logging will fall back to JUL (`java.util.logging`).

The logger name for the *Vaadin* module is `com.holonplatform.vaadin`.

== System requirements

=== Java

The Holon Platform Vaadin module requires https://www.java.com[Java] *8* or higher.

=== Vaadin

The Holon Platform Vaadin module requires https://vaadin.com[Vaadin] *8.1* or higher.
